llm:
  - type : "azureopenai"
    api_key: "<>"  # Replace with your Azure OpenAI API key
    base_url: "<>"  # Replace with your Azure OpenAI endpoint
    model: "gpt-4o"  # Options: gpt-4o, gpt-4.1
    api_version: "2025-01-01-preview"  # Adjust based on your Azure OpenAI API version, default is 2025-01-01-preview
    temperature: 0

  - type: "googlegenai"
    api_key: "your-googlegenai-api-key-here"  # Replace with your Google API key
    # base_url: "https://generativelanguage.googleapis.com/v1beta" # Optional, default is the main endpoint
    model: "gemini-2.0-flash-001" # gemini-1.5-pro, gemini-2.0-flash-001, etc.
    temperature: 0

  - type: "claude"  
    api_key: "your-anthropic-api-key-here"  
    # base_url: "https://api.anthropic.com/v1" # optional, default is the main endpoint
    model: "claude-3-5-haiku-latest"  # Options: claude-3-5-sonnet, claude-3-opus, etc.
    temperature: 0

    
  - type: "openai"
    api_key: "your-openai-api-key-here"
    # base_url: "https://api.openai.com/v1"
    model: "gpt-4o"  # Options: gpt-4o, gpt-4-turbo, gpt-3.5-turbo, etc.
    temperature: 0
